// The facts in a document header, from the repo rather than from memory.
//
// OUTSTANDING.md said "Live on production: 43c5158. Tests 933 pass." Both were
// true when somebody typed them and neither was true a day later — it was
// 746de98 and 1,076 by the time anyone noticed. A number nobody can be bothered
// to update is a number that quietly becomes a lie, and this file is read
// precisely by people deciding what to work on next.
//
//   node scripts/doc-header.mjs           print what the marked block should say
//   node scripts/doc-header.mjs --write   rewrite it in place
//
// It fills the block between the two markers and touches nothing else. Prose
// around it stays prose; only the facts are generated.
//
// tests/doc-claims.test.ts checks the block is present and current, so a header
// that has drifted fails rather than misleading.

import fs from 'node:fs';
import { execSync } from 'node:child_process';

const DOC = new URL('../OUTSTANDING.md', import.meta.url);
const OPEN = '<!-- generated: do not edit by hand -->';
const CLOSE = '<!-- /generated -->';

function git(cmd) {
    try {
        return execSync('git ' + cmd, { cwd: new URL('..', import.meta.url), stdio: ['ignore', 'pipe', 'ignore'] })
            .toString().trim();
    } catch {
        return null;
    }
}

// What is actually live. check-deploy.mjs asks Vercel; this asks git, which is
// the same answer whenever master is deployed and is honest about being a
// different question when it is not.
const head = git('rev-parse --short origin/master') || git('rev-parse --short HEAD') || 'unknown';
const when = git("log -1 --format=%cs origin/master") || git('log -1 --format=%cs') || 'unknown';

// The test count, from the suite rather than from a memory of the suite.
let tests = 'unknown';
try {
    const out = execSync('npm test', {
        cwd: new URL('..', import.meta.url),
        stdio: ['ignore', 'pipe', 'pipe'],
        encoding: 'utf8',
    });
    const pass = out.match(/^# pass (\d+)$/m);
    const fail = out.match(/^# fail (\d+)$/m);
    if (pass) tests = Number(fail && fail[1]) > 0
        ? pass[1] + ' pass, **' + fail[1] + ' FAIL**'
        : pass[1] + ' pass';
} catch (err) {
    tests = 'the suite did not finish';
}

const migrations = fs.readdirSync(new URL('../supabase/migrations/', import.meta.url))
    .filter((n) => n.endsWith('.sql')).length;

const block = [
    OPEN,
    '',
    '| | |',
    '|---|---|',
    '| master | `' + head + '`, ' + when + ' |',
    '| tests | ' + tests + ' |',
    '| migrations | ' + migrations + ' |',
    '',
    'Generated by `node scripts/doc-header.mjs --write`. Do not type these in.',
    '',
    CLOSE,
].join('\n');

if (!process.argv.includes('--write')) {
    console.log('\n' + block + '\n');
    process.exit(0);
}

const body = fs.readFileSync(DOC, 'utf8');
const start = body.indexOf(OPEN);
const end = body.indexOf(CLOSE);

if (start === -1 || end === -1) {
    console.error('\n  OUTSTANDING.md has no generated block. Add these two lines where it goes:\n');
    console.error('    ' + OPEN);
    console.error('    ' + CLOSE + '\n');
    process.exit(1);
}

fs.writeFileSync(DOC, body.slice(0, start) + block + body.slice(end + CLOSE.length));
console.log('\n  OUTSTANDING.md header updated.\n');
